FROM python:3.10-slim

# Variables de entorno
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Crear y establecer directorio de trabajo
WORKDIR /app

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    libglib2.0-0 libsm6 libxrender1 libxext6 \
    ffmpeg libgtk2.0-dev libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*

# Copiar archivos y dependencias
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copiar el resto del código
COPY . .

# Exponer el puerto de Django
EXPOSE 8000

# Comando para iniciar el servidor
CMD ["gunicorn", "backend.wsgi:application", "--bind", "0.0.0.0:8000"]
